### ISSUE TITLE
Array indentation seems broken

### ISSUE THREAD

**Issue by j0ni** [lunaryorn/puppet-mode#33]
Multiline array literals get formatted like this:

```
  $nodes = [
            '10.116.1.72',
            '10.116.1.73'
            ]
```

which seems quite broken. I think they should look like this:

```
  $nodes = [
    '10.116.1.72',
    '10.116.1.73'
  ]
```

**Comment by askreet** [comment]
Aw, just saw this after fixing this indentation locally. Can I convince you to accept a pull request addressing this while you're working out the details of SMIE?
